# -*- coding: utf-8 -*-
"""Data Collection and Split

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqCQH1fHq3tNThDDtkEqUjpbzQO7D7az
"""

Flair= nib.load('/BraTS20_Training_008/BraTS20_Training_008_flair.nii')
Seg= nib.load('/BraTS20_Training_008/BraTS20_Training_008_seg.nii')
T1= nib.load('/BraTS20_Training_008/BraTS20_Training_008_t1.nii')
T1ce= nib.load('/BraTS20_Training_008/BraTS20_Training_008_t1ce.nii')
T2= nib.load('/BraTS20_Training_008/BraTS20_Training_008_t2.nii')

plotting.plot_anat(Flair,cut_coords=[-100, 100, 100],title="Flair",draw_cross =False)
plotting.plot_anat(Seg,cut_coords=[-100, 100, 100],title="Seg",draw_cross =False)
plotting.plot_anat(T1,cut_coords=[-100, 100, 100],title="T1",draw_cross =False)
plotting.plot_anat(T1ce,cut_coords=[-100, 100, 100],title="T1ce",draw_cross =False)
plotting.plot_anat(T2,cut_coords=[-100, 100, 100],title="T2",draw_cross =False)

Path= '/MICCAI_BraTS2020_TrainingData'
p=os.listdir(Path)

Input_Data= []
def Data_Preprocessing(modalities_dir):
    all_modalities = []
    for modality in modalities_dir:
        nifti_file   = nib.load(modality)
        brain_numpy  = np.asarray(nifti_file.dataobj)
        all_modalities.append(brain_numpy)
    brain_affine   = nifti_file.affine
    all_modalities = np.array(all_modalities)
    all_modalities = np.rint(all_modalities).astype(np.int16)
    all_modalities = all_modalities[:, :, :, :]
    all_modalities = np.transpose(all_modalities)
    return all_modalities
for i in p[:20]:
    brain_dir = os.path.normpath(Path+'/'+i)
    flair     = glob.glob(os.path.join(brain_dir, '*_flair*.nii'))
    t1        = glob.glob(os.path.join(brain_dir, '*_t1*.nii'))
    t1ce      = glob.glob(os.path.join(brain_dir, '*_t1ce*.nii'))
    t2        = glob.glob(os.path.join(brain_dir, '*_t2*.nii'))
    gt        = glob.glob( os.path.join(brain_dir, '*_seg*.nii'))
    modalities_dir = [flair[0], t1[0], t1ce[0], t2[0], gt[0]]
    P_Data = Data_Preprocessing(modalities_dir)
    Input_Data.append(P_Data)

fig = plt.figure(figsize=(5,5))
immmg = Input_Data[1][120,:,:,3]
imgplot = plt.imshow(immmg)
plt.show()

def Data_Concatenate(Input_Data):
    counter=0
    Output= []
    for i in range(5):
        print('$')
        c=0
        counter=0
        for ii in range(len(Input_Data)):
            if (counter != len(Input_Data)):
                a= Input_Data[counter][:,:,:,i]
                #print('a={}'.format(a.shape))
                b= Input_Data[counter+1][:,:,:,i]
                #print('b={}'.format(b.shape))
                if(counter==0):
                    c= np.concatenate((a, b), axis=0)
                    print('c1={}'.format(c.shape))
                    counter= counter+2
                else:
                    c1= np.concatenate((a, b), axis=0)
                    c= np.concatenate((c, c1), axis=0)
                    print('c2={}'.format(c.shape))
                    counter= counter+2
        c= c[:,:,:,np.newaxis]
        Output.append(c)
    return Output

InData= Data_Concatenate(Input_Data)

AIO= concatenate(InData, axis=3)
AIO=np.array(AIO,dtype='float32')
TR=np.array(AIO[:,:,:,1],dtype='float32')
TRL=np.array(AIO[:,:,:,4],dtype='float32')

X_train , X_test, Y_train, Y_test = train_test_split(TR, TRL, test_size=0.15, random_state=32)
AIO=TRL=0