# -*- coding: utf-8 -*-
"""Model Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqCQH1fHq3tNThDDtkEqUjpbzQO7D7az
"""

# Fitting the model over the data
history = model.fit(X_train,Y_train,batch_size=32,epochs=40,validation_split=0.20,verbose=1,initial_epoch=0)

# Evaluating the model on the training and testing data
model.evaluate(x=X_train, y=Y_train, batch_size=32 , verbose=1, sample_weight=None, steps=None)
model.evaluate(x=X_test, y=Y_test, batch_size=32, verbose=1, sample_weight=None, steps=None)